sudo: required

language: node_js
node_js:
  - "6"

services:
  - docker

install:
  - cd test/dummy && yarn && cd - # (the dash means back to previous dir)

script:
  - ./test/test.sh

after_script:
  - docker rm -f docker-nuxt-test
  - docker images -q | xargs docker rmi -f
